# Generated by Django 3.2.4 on 2021-06-10 17:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccount', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='working_hours',
        ),
        migrations.AddField(
            model_name='employee',
            name='working_hours_from',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='employee',
            name='working_hours_to',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employment_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.IntegerField(blank=True, max_length=8),
        ),
    ]
