# Generated by Django 3.2.4 on 2021-06-10 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccount', '0002_auto_20210610_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('FT', 'Full_Time'), ('PT', 'Part_Time'), ('Temp', 'Temporary'), ('S', 'Seasonal')], max_length=29),
        ),
    ]
