# Generated by Django 3.2.4 on 2021-06-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccount', '0004_auto_20210610_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='position',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='team',
            name='team',
            field=models.CharField(max_length=255),
        ),
    ]
