# Generated by Django 3.2.4 on 2021-06-10 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccount', '0005_auto_20210610_1828'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='employee',
        ),
    ]
