# Generated by Django 3.2.4 on 2021-06-11 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccount', '0006_alter_employee_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='emp_details',
        ),
    ]
