# Generated by Django 3.2.4 on 2021-06-11 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccount', '0007_alter_employee_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='employee',
        ),
    ]
